package com.abovebytes.paymentswitch.domain.enums;

import lombok.Getter;

@Getter
public enum AppEnums {
    STRIPE_TEST_PRIVATE_SECRET_KEY,
    STRIPE_LIVE_PRIVATE_SECRET_KEY,
    STRIPE_TEST_PUBLISHABLE_KEY,
    STRIPE_TEST_MODE,
    STRIPE_AGGREGATOR_FEE_PERCENT,
    usd,
    cdf,
    DEFAULT_MERCHANT_ONBOARDING_REFRESH_URL,
    DEFAULT_MERCHANT_ONBOARDING_RETURN_URL,
    close_browser,
    http,
    https,
    US,
    STRIPE_USE_SNAPSHOT_WEBHOOK,
    STRIPE_TEST_WEBHOOK_SNAPSHOT_SIGNING_SECRET,
    STRIPE_TEST_WEBHOOK_THIN_SIGNING_SECRET,
    STRIPE_LOCAL_SIGNING_KEY,
    STRIPE_LIVE_WEBHOOK_THIN,
    STRIPE_LIVE_WEBHOOK_SNAPSHOT,
    UNKNOWN,
    CC_PAY_API_USER_PASSWORD,
    CC_PAY_API_USER,
    CC_PAY_URL,
    CC_PAY_AUTH_URI,
    CC_PAY_AUTH_REFRESH_URI
}

